"""
app/api/v1/endpoints/recommendations.py
─────────────────────────────────────────
POST /recommendations  – ML-ranked internship list for the current user
"""

from fastapi import APIRouter

from app.core.deps import DB, CurrentUserId
from app.schemas.internship import RecommendationRequest, RecommendationResponse
from app.services.recommendation_service import get_recommendations

router = APIRouter(prefix="/recommendations", tags=["recommendations"])


@router.post("", response_model=RecommendationResponse)
async def recommendations(
    payload: RecommendationRequest,
    db: DB,
    current_user: CurrentUserId,
):
    """
    Accepts user profile features and returns a ranked list of internships
    with confidence (match) scores generated by the Random Forest model.
    """
    ranked = await get_recommendations(db, current_user, payload)
    return RecommendationResponse(recommendations=ranked)
