"""
scripts/seed_db.py
───────────────────
Seeds MongoDB with 40 realistic internship listings.

Run from the project root:
    python scripts/seed_db.py

Requires a running MongoDB instance and a valid .env file.
"""

import asyncio
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from motor.motor_asyncio import AsyncIOMotorClient
from app.core.config import settings

INTERNSHIPS = [
    # ── AI / ML ──────────────────────────────────────────────────────────────
    {
        "title": "ML Research Intern",
        "company": "Amazon",
        "company_logo": "https://logo.clearbit.com/amazon.com",
        "location": "Remote",
        "type": "Remote",
        "skills": ["Python", "scikit-learn", "PyTorch", "TensorFlow"],
        "duration": "6 months",
        "stipend": "₹60,000/mo",
        "domain": "AI/ML",
        "description": "Build recommendation systems for Amazon's product suite. Work with large-scale datasets and ship ML features to production.",
        "apply_url": "https://amazon.jobs",
    },
    {
        "title": "Data Science Intern",
        "company": "Flipkart",
        "company_logo": "https://logo.clearbit.com/flipkart.com",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["Python", "SQL", "Pandas", "ML"],
        "duration": "4 months",
        "stipend": "₹40,000/mo",
        "domain": "Data Science",
        "description": "Analyse large-scale e-commerce data to improve product recommendations and pricing algorithms.",
        "apply_url": "https://flipkart.com/careers",
    },
    {
        "title": "AI/ML Intern",
        "company": "NVIDIA",
        "company_logo": "https://logo.clearbit.com/nvidia.com",
        "location": "Hyderabad, India",
        "type": "On-site",
        "skills": ["Python", "CUDA", "PyTorch", "TensorFlow"],
        "duration": "6 months",
        "stipend": "₹75,000/mo",
        "domain": "AI/ML",
        "description": "Work on GPU-accelerated ML training pipelines and optimise inference latency for edge devices.",
        "apply_url": "https://nvidia.com/en-us/about-nvidia/careers/",
    },
    {
        "title": "NLP Research Intern",
        "company": "Microsoft",
        "company_logo": "https://logo.clearbit.com/microsoft.com",
        "location": "Hyderabad, India",
        "type": "Hybrid",
        "skills": ["Python", "PyTorch", "scikit-learn", "REST APIs"],
        "duration": "3 months",
        "stipend": "₹70,000/mo",
        "domain": "AI/ML",
        "description": "Research and prototype transformer-based NLP features for Microsoft Bing and Azure Cognitive Services.",
        "apply_url": "https://careers.microsoft.com",
    },
    # ── App Dev ───────────────────────────────────────────────────────────────
    {
        "title": "Flutter Developer Intern",
        "company": "Google",
        "company_logo": "https://logo.clearbit.com/google.com",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["Flutter", "Dart", "Firebase"],
        "duration": "3 months",
        "stipend": "₹50,000/mo",
        "domain": "App Dev",
        "description": "Work on Flutter-based developer tools used by millions of engineers worldwide.",
        "apply_url": "https://careers.google.com",
    },
    {
        "title": "iOS/Android Intern",
        "company": "CRED",
        "company_logo": "https://logo.clearbit.com/cred.club",
        "location": "Bangalore, India",
        "type": "On-site",
        "skills": ["Flutter", "Swift", "Kotlin"],
        "duration": "3 months",
        "stipend": "₹55,000/mo",
        "domain": "App Dev",
        "description": "Build next-gen fintech mobile features at scale. Own entire features from design to deployment.",
        "apply_url": "https://cred.club/careers",
    },
    {
        "title": "Android Developer Intern",
        "company": "Zomato",
        "company_logo": "https://logo.clearbit.com/zomato.com",
        "location": "Gurugram, India",
        "type": "On-site",
        "skills": ["Kotlin", "Java", "Firebase", "REST APIs"],
        "duration": "4 months",
        "stipend": "₹45,000/mo",
        "domain": "App Dev",
        "description": "Develop features in the Zomato Android app serving 80M+ monthly active users.",
        "apply_url": "https://zomato.com/careers",
    },
    {
        "title": "React Native Intern",
        "company": "Swiggy",
        "company_logo": "https://logo.clearbit.com/swiggy.com",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["React", "TypeScript", "REST APIs", "Firebase"],
        "duration": "3 months",
        "stipend": "₹40,000/mo",
        "domain": "App Dev",
        "description": "Own and ship consumer-facing features in the Swiggy app across iOS and Android.",
        "apply_url": "https://swiggy.com/careers",
    },
    # ── Web Dev ───────────────────────────────────────────────────────────────
    {
        "title": "Full Stack Intern",
        "company": "Razorpay",
        "company_logo": "https://logo.clearbit.com/razorpay.com",
        "location": "Bangalore, India",
        "type": "On-site",
        "skills": ["React", "Node.js", "PostgreSQL"],
        "duration": "3 months",
        "stipend": "₹45,000/mo",
        "domain": "Web",
        "description": "Work on fintech products serving 8M+ businesses. Contribute to payment gateway APIs and merchant dashboard.",
        "apply_url": "https://razorpay.com/jobs",
    },
    {
        "title": "Frontend Intern",
        "company": "Atlassian",
        "company_logo": "https://logo.clearbit.com/atlassian.com",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["React", "TypeScript", "GraphQL"],
        "duration": "6 months",
        "stipend": "₹65,000/mo",
        "domain": "Web",
        "description": "Build performant UI components for Jira and Confluence used by 10M+ teams globally.",
        "apply_url": "https://atlassian.com/company/careers",
    },
    {
        "title": "Backend Intern",
        "company": "Freshworks",
        "company_logo": "https://logo.clearbit.com/freshworks.com",
        "location": "Chennai, India",
        "type": "On-site",
        "skills": ["Node.js", "PostgreSQL", "REST APIs", "Docker"],
        "duration": "3 months",
        "stipend": "₹35,000/mo",
        "domain": "Web",
        "description": "Design and implement scalable backend microservices for Freshdesk's CRM platform.",
        "apply_url": "https://freshworks.com/company/careers/",
    },
    {
        "title": "Next.js Developer Intern",
        "company": "Vercel",
        "company_logo": "https://logo.clearbit.com/vercel.com",
        "location": "Remote",
        "type": "Remote",
        "skills": ["Next.js", "TypeScript", "React", "Node.js"],
        "duration": "3 months",
        "stipend": "₹55,000/mo",
        "domain": "Web",
        "description": "Contribute to the Vercel platform and Next.js open-source framework used by millions of developers.",
        "apply_url": "https://vercel.com/careers",
    },
    {
        "title": "GraphQL API Intern",
        "company": "Hasura",
        "company_logo": "https://logo.clearbit.com/hasura.io",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["GraphQL", "Node.js", "PostgreSQL", "Docker"],
        "duration": "4 months",
        "stipend": "₹40,000/mo",
        "domain": "Web",
        "description": "Work on Hasura's open-source GraphQL engine and enterprise cloud offering.",
        "apply_url": "https://hasura.io/careers/",
    },
    # ── Cloud ─────────────────────────────────────────────────────────────────
    {
        "title": "Cloud Solutions Intern",
        "company": "Google Cloud",
        "company_logo": "https://logo.clearbit.com/google.com",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["GCP", "Docker", "Python", "REST APIs"],
        "duration": "6 months",
        "stipend": "₹60,000/mo",
        "domain": "Cloud",
        "description": "Help enterprise customers design and migrate workloads to Google Cloud Platform.",
        "apply_url": "https://careers.google.com",
    },
    {
        "title": "AWS Cloud Intern",
        "company": "Amazon Web Services",
        "company_logo": "https://logo.clearbit.com/aws.amazon.com",
        "location": "Hyderabad, India",
        "type": "On-site",
        "skills": ["AWS", "Python", "Docker", "SQL"],
        "duration": "6 months",
        "stipend": "₹65,000/mo",
        "domain": "Cloud",
        "description": "Build internal tooling and infrastructure automation for AWS service teams.",
        "apply_url": "https://amazon.jobs",
    },
    {
        "title": "Cloud Infrastructure Intern",
        "company": "Infosys",
        "company_logo": "https://logo.clearbit.com/infosys.com",
        "location": "Pune, India",
        "type": "On-site",
        "skills": ["AWS", "Docker", "Python", "Git"],
        "duration": "3 months",
        "stipend": "₹25,000/mo",
        "domain": "Cloud",
        "description": "Assist cloud architects in designing multi-cloud solutions for Fortune 500 clients.",
        "apply_url": "https://infosys.com/careers",
    },
    # ── DevOps ────────────────────────────────────────────────────────────────
    {
        "title": "DevOps Intern",
        "company": "ThoughtWorks",
        "company_logo": "https://logo.clearbit.com/thoughtworks.com",
        "location": "Pune, India",
        "type": "Hybrid",
        "skills": ["Docker", "Git", "AWS", "Python"],
        "duration": "3 months",
        "stipend": "₹30,000/mo",
        "domain": "DevOps",
        "description": "Automate CI/CD pipelines and infrastructure provisioning for client delivery teams.",
        "apply_url": "https://thoughtworks.com/careers",
    },
    {
        "title": "Site Reliability Intern",
        "company": "Zepto",
        "company_logo": "https://logo.clearbit.com/zeptonow.com",
        "location": "Mumbai, India",
        "type": "On-site",
        "skills": ["Docker", "AWS", "Python", "SQL"],
        "duration": "3 months",
        "stipend": "₹35,000/mo",
        "domain": "DevOps",
        "description": "Monitor and improve reliability of Zepto's real-time 10-minute delivery infrastructure.",
        "apply_url": "https://zeptonow.com/careers",
    },
    # ── Cybersecurity ─────────────────────────────────────────────────────────
    {
        "title": "Security Analyst Intern",
        "company": "Wipro",
        "company_logo": "https://logo.clearbit.com/wipro.com",
        "location": "Bangalore, India",
        "type": "On-site",
        "skills": ["Python", "REST APIs", "SQL"],
        "duration": "3 months",
        "stipend": "₹28,000/mo",
        "domain": "Cybersecurity",
        "description": "Perform vulnerability assessments, penetration testing, and security code reviews for enterprise clients.",
        "apply_url": "https://wipro.com/careers",
    },
    {
        "title": "AppSec Intern",
        "company": "Razorpay",
        "company_logo": "https://logo.clearbit.com/razorpay.com",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["Python", "REST APIs", "Node.js"],
        "duration": "3 months",
        "stipend": "₹40,000/mo",
        "domain": "Cybersecurity",
        "description": "Work with the security team to harden payment APIs and conduct threat modelling on new features.",
        "apply_url": "https://razorpay.com/jobs",
    },
    # ── UI/UX ─────────────────────────────────────────────────────────────────
    {
        "title": "Product Design Intern",
        "company": "Figma",
        "company_logo": "https://logo.clearbit.com/figma.com",
        "location": "Remote",
        "type": "Remote",
        "skills": ["Flutter", "React"],
        "duration": "3 months",
        "stipend": "₹50,000/mo",
        "domain": "UI/UX",
        "description": "Redesign core flows in Figma's web and desktop apps based on real user research.",
        "apply_url": "https://figma.com/careers",
    },
    {
        "title": "UX Research Intern",
        "company": "Meesho",
        "company_logo": "https://logo.clearbit.com/meesho.com",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["Flutter", "React"],
        "duration": "3 months",
        "stipend": "₹32,000/mo",
        "domain": "UI/UX",
        "description": "Conduct usability studies and qualitative research to improve shopping experience for 140M+ users.",
        "apply_url": "https://meesho.com/careers",
    },
    # ── Blockchain ────────────────────────────────────────────────────────────
    {
        "title": "Blockchain Developer Intern",
        "company": "Polygon",
        "company_logo": "https://logo.clearbit.com/polygon.technology",
        "location": "Remote",
        "type": "Remote",
        "skills": ["Python", "Node.js", "REST APIs"],
        "duration": "3 months",
        "stipend": "₹40,000/mo",
        "domain": "Blockchain",
        "description": "Contribute to Polygon's Layer-2 Ethereum scaling solutions and DeFi tooling.",
        "apply_url": "https://polygon.technology/careers",
    },
    {
        "title": "Web3 Intern",
        "company": "CoinDCX",
        "company_logo": "https://logo.clearbit.com/coindcx.com",
        "location": "Mumbai, India",
        "type": "Hybrid",
        "skills": ["Python", "Node.js", "TypeScript"],
        "duration": "3 months",
        "stipend": "₹35,000/mo",
        "domain": "Blockchain",
        "description": "Build DeFi products and smart contract integrations on India's largest crypto exchange.",
        "apply_url": "https://coindcx.com/careers",
    },
    # ── Game Dev ──────────────────────────────────────────────────────────────
    {
        "title": "Game Developer Intern",
        "company": "Nazara Technologies",
        "company_logo": "https://logo.clearbit.com/nazara.com",
        "location": "Mumbai, India",
        "type": "On-site",
        "skills": ["Python", "TypeScript"],
        "duration": "3 months",
        "stipend": "₹25,000/mo",
        "domain": "Game Dev",
        "description": "Develop casual mobile games and real-money gaming features for 100M+ players across Asia.",
        "apply_url": "https://nazara.com/careers",
    },
    {
        "title": "Unity Game Dev Intern",
        "company": "Dream11",
        "company_logo": "https://logo.clearbit.com/dream11.com",
        "location": "Mumbai, India",
        "type": "Hybrid",
        "skills": ["Python", "TypeScript", "Node.js"],
        "duration": "3 months",
        "stipend": "₹30,000/mo",
        "domain": "Game Dev",
        "description": "Build gamification layers and live-score features for India's largest sports gaming platform.",
        "apply_url": "https://dream11.com/careers",
    },
    # ── More mixed listings ───────────────────────────────────────────────────
    {
        "title": "Backend Intern – Payments",
        "company": "PhonePe",
        "company_logo": "https://logo.clearbit.com/phonepe.com",
        "location": "Bangalore, India",
        "type": "On-site",
        "skills": ["Java", "SQL", "Docker", "REST APIs"],
        "duration": "4 months",
        "stipend": "₹50,000/mo",
        "domain": "Web",
        "description": "Build low-latency payment processing services handling ₹1Cr+ transactions per day.",
        "apply_url": "https://phonepe.com/en/careers.html",
    },
    {
        "title": "Data Engineering Intern",
        "company": "Ola",
        "company_logo": "https://logo.clearbit.com/olacabs.com",
        "location": "Bangalore, India",
        "type": "On-site",
        "skills": ["Python", "SQL", "GCP", "Pandas"],
        "duration": "4 months",
        "stipend": "₹38,000/mo",
        "domain": "Data Science",
        "description": "Build data pipelines and dashboards to power operations analytics for 150+ cities.",
        "apply_url": "https://olacabs.com/careers",
    },
    {
        "title": "iOS Developer Intern",
        "company": "Groww",
        "company_logo": "https://logo.clearbit.com/groww.in",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["Swift", "REST APIs", "Firebase"],
        "duration": "3 months",
        "stipend": "₹45,000/mo",
        "domain": "App Dev",
        "description": "Work on the Groww iOS app helping 40M+ investors manage their portfolios.",
        "apply_url": "https://groww.in/careers",
    },
    {
        "title": "ML Platform Intern",
        "company": "Uber",
        "company_logo": "https://logo.clearbit.com/uber.com",
        "location": "Hyderabad, India",
        "type": "Hybrid",
        "skills": ["Python", "scikit-learn", "SQL", "Docker"],
        "duration": "6 months",
        "stipend": "₹70,000/mo",
        "domain": "AI/ML",
        "description": "Work on Michelangelo, Uber's internal ML platform serving thousands of production models.",
        "apply_url": "https://uber.com/careers",
    },
    {
        "title": "Full Stack Intern",
        "company": "Notion",
        "company_logo": "https://logo.clearbit.com/notion.so",
        "location": "Remote",
        "type": "Remote",
        "skills": ["React", "TypeScript", "Node.js", "PostgreSQL"],
        "duration": "3 months",
        "stipend": "₹55,000/mo",
        "domain": "Web",
        "description": "Contribute to Notion's editor and collaboration features used by 30M+ people.",
        "apply_url": "https://notion.com/careers",
    },
    {
        "title": "Infra & SRE Intern",
        "company": "Hotstar",
        "company_logo": "https://logo.clearbit.com/hotstar.com",
        "location": "Mumbai, India",
        "type": "On-site",
        "skills": ["AWS", "Docker", "Python", "SQL"],
        "duration": "3 months",
        "stipend": "₹40,000/mo",
        "domain": "Cloud",
        "description": "Help scale streaming infrastructure that handles 50M+ concurrent viewers during live cricket events.",
        "apply_url": "https://hotstar.com/in/jobs",
    },
    {
        "title": "Computer Vision Intern",
        "company": "Niramai",
        "company_logo": "https://logo.clearbit.com/niramai.com",
        "location": "Bangalore, India",
        "type": "On-site",
        "skills": ["Python", "PyTorch", "scikit-learn", "TensorFlow"],
        "duration": "4 months",
        "stipend": "₹35,000/mo",
        "domain": "AI/ML",
        "description": "Develop deep learning models for medical imaging — helping detect breast cancer non-invasively.",
        "apply_url": "https://niramai.com/careers/",
    },
    {
        "title": "DevOps & Platform Intern",
        "company": "Setu",
        "company_logo": "https://logo.clearbit.com/setu.co",
        "location": "Bangalore, India",
        "type": "Hybrid",
        "skills": ["Docker", "AWS", "Python", "Git"],
        "duration": "3 months",
        "stipend": "₹32,000/mo",
        "domain": "DevOps",
        "description": "Maintain and improve developer infrastructure powering India's fastest-growing fintech API platform.",
        "apply_url": "https://setu.co/careers",
    },
    {
        "title": "Product Analytics Intern",
        "company": "Lenskart",
        "company_logo": "https://logo.clearbit.com/lenskart.com",
        "location": "Delhi, India",
        "type": "On-site",
        "skills": ["Python", "SQL", "Pandas"],
        "duration": "3 months",
        "stipend": "₹28,000/mo",
        "domain": "Data Science",
        "description": "Drive product decisions using data for India's largest omnichannel eyewear brand.",
        "apply_url": "https://lenskart.com/careers",
    },
    {
        "title": "API Backend Intern",
        "company": "Zerodha",
        "company_logo": "https://logo.clearbit.com/zerodha.com",
        "location": "Bangalore, India",
        "type": "On-site",
        "skills": ["Python", "FastAPI", "PostgreSQL", "REST APIs"],
        "duration": "4 months",
        "stipend": "₹50,000/mo",
        "domain": "Web",
        "description": "Build trading APIs powering India's largest stockbroker serving 7M+ active investors.",
        "apply_url": "https://zerodha.com/careers",
    },
    {
        "title": "Flutter & Firebase Intern",
        "company": "upGrad",
        "company_logo": "https://logo.clearbit.com/upgrad.com",
        "location": "Mumbai, India",
        "type": "Hybrid",
        "skills": ["Flutter", "Dart", "Firebase", "REST APIs"],
        "duration": "3 months",
        "stipend": "₹30,000/mo",
        "domain": "App Dev",
        "description": "Build features in upGrad's learning app serving 3M+ learners pursuing career transitions.",
        "apply_url": "https://upgrad.com/careers",
    },
]


async def seed():
    now = datetime.now(timezone.utc)
    client = AsyncIOMotorClient(settings.MONGODB_URL)
    db = client[settings.MONGODB_DB_NAME]

    # Wipe existing internships
    await db.internships.delete_many({})
    print("Cleared existing internship listings.")

    # Stagger dates for realism
    docs = []
    for i, intern in enumerate(INTERNSHIPS):
        doc = dict(intern)
        doc["posted_at"] = now - timedelta(days=i % 10)
        doc["deadline"] = now + timedelta(days=14 + (i % 20))
        docs.append(doc)

    result = await db.internships.insert_many(docs)
    print(f"✅ Inserted {len(result.inserted_ids)} internship listings.")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
